# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiv1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_3/over.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 802, 482))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(790, 440))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 480))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe Print"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.OverTab = QtGui.QWidget()
        self.OverTab.setObjectName(_fromUtf8("OverTab"))
        self.background = QtGui.QLabel(self.OverTab)
        self.background.setGeometry(QtCore.QRect(0, 0, 801, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        self.background.setText(_fromUtf8(""))
        self.background.setPixmap(QtGui.QPixmap(_fromUtf8("background/backoverNeww.jpg")))
        self.background.setScaledContents(True)
        self.background.setWordWrap(False)
        self.background.setObjectName(_fromUtf8("background"))
        self.calendarWidget = QtGui.QCalendarWidget(self.OverTab)
        self.calendarWidget.setGeometry(QtCore.QRect(560, 10, 217, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtGui.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.timeEdit = QtGui.QTimeEdit(self.OverTab)
        self.timeEdit.setGeometry(QtCore.QRect(47, 36, 87, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe Print"))
        font.setPointSize(18)
        self.timeEdit.setFont(font)
        self.timeEdit.setStatusTip(_fromUtf8(""))
        self.timeEdit.setAutoFillBackground(True)
        self.timeEdit.setWrapping(False)
        self.timeEdit.setFrame(False)
        self.timeEdit.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.timeEdit.setTime(QtCore.QTime(10, 51, 0))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.label_6 = QtGui.QLabel(self.OverTab)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 128, 65))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("time_frame/frame5.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.temp_val = QtGui.QLCDNumber(self.OverTab)
        self.temp_val.setGeometry(QtCore.QRect(60, 130, 181, 61))
        self.temp_val.setFrameShape(QtGui.QFrame.StyledPanel)
        self.temp_val.setFrameShadow(QtGui.QFrame.Raised)
        self.temp_val.setSmallDecimalPoint(False)
        self.temp_val.setDigitCount(7)
        self.temp_val.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.temp_val.setObjectName(_fromUtf8("temp_val"))
        self.IrrigVal = QtGui.QLCDNumber(self.OverTab)
        self.IrrigVal.setGeometry(QtCore.QRect(60, 270, 181, 71))
        self.IrrigVal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.IrrigVal.setFrameShadow(QtGui.QFrame.Raised)
        self.IrrigVal.setSmallDecimalPoint(False)
        self.IrrigVal.setDigitCount(7)
        self.IrrigVal.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.IrrigVal.setObjectName(_fromUtf8("IrrigVal"))
        self.HumidityVal = QtGui.QLCDNumber(self.OverTab)
        self.HumidityVal.setGeometry(QtCore.QRect(480, 130, 91, 61))
        self.HumidityVal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.HumidityVal.setFrameShadow(QtGui.QFrame.Raised)
        self.HumidityVal.setSmallDecimalPoint(False)
        self.HumidityVal.setDigitCount(4)
        self.HumidityVal.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.HumidityVal.setObjectName(_fromUtf8("HumidityVal"))
        self.LumVal = QtGui.QLCDNumber(self.OverTab)
        self.LumVal.setGeometry(QtCore.QRect(510, 280, 201, 61))
        self.LumVal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LumVal.setFrameShadow(QtGui.QFrame.Raised)
        self.LumVal.setSmallDecimalPoint(False)
        self.LumVal.setDigitCount(7)
        self.LumVal.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.LumVal.setObjectName(_fromUtf8("LumVal"))
        self.HumidityVal_S = QtGui.QLCDNumber(self.OverTab)
        self.HumidityVal_S.setGeometry(QtCore.QRect(640, 130, 91, 61))
        self.HumidityVal_S.setFrameShape(QtGui.QFrame.StyledPanel)
        self.HumidityVal_S.setFrameShadow(QtGui.QFrame.Raised)
        self.HumidityVal_S.setSmallDecimalPoint(False)
        self.HumidityVal_S.setDigitCount(4)
        self.HumidityVal_S.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.HumidityVal_S.setProperty("intValue", 0)
        self.HumidityVal_S.setObjectName(_fromUtf8("HumidityVal_S"))
        self.UP = QtGui.QPushButton(self.OverTab)
        self.UP.setGeometry(QtCore.QRect(344, 110, 71, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.UP.setFont(font)
        self.UP.setText(_fromUtf8(""))
        self.UP.setFlat(True)
        self.UP.setObjectName(_fromUtf8("UP"))
        self.DOWN = QtGui.QPushButton(self.OverTab)
        self.DOWN.setGeometry(QtCore.QRect(350, 280, 71, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.DOWN.setFont(font)
        self.DOWN.setText(_fromUtf8(""))
        self.DOWN.setFlat(True)
        self.DOWN.setObjectName(_fromUtf8("DOWN"))
        self.label_8 = QtGui.QLabel(self.OverTab)
        self.label_8.setGeometry(QtCore.QRect(250, 135, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.OverTab)
        self.label_9.setGeometry(QtCore.QRect(250, 282, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.OverTab)
        self.label_10.setGeometry(QtCore.QRect(710, 290, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.OverTab)
        self.label_11.setGeometry(QtCore.QRect(570, 130, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_11.setFont(font)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.OverTab)
        self.label_12.setGeometry(QtCore.QRect(730, 130, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_12.setFont(font)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_2/over.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.OverTab, icon1, _fromUtf8(""))
        self.TempTab = QtGui.QWidget()
        self.TempTab.setObjectName(_fromUtf8("TempTab"))
        self.TempC = QtGui.QLabel(self.TempTab)
        self.TempC.setGeometry(QtCore.QRect(0, 0, 807, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempC.sizePolicy().hasHeightForWidth())
        self.TempC.setSizePolicy(sizePolicy)
        self.TempC.setText(_fromUtf8(""))
        self.TempC.setPixmap(QtGui.QPixmap(_fromUtf8("background/TempBack1.jpg")))
        self.TempC.setScaledContents(True)
        self.TempC.setObjectName(_fromUtf8("TempC"))
        self.dial_Temp = QtGui.QDial(self.TempTab)
        self.dial_Temp.setGeometry(QtCore.QRect(538, 151, 242, 234))
        self.dial_Temp.setMinimum(10)
        self.dial_Temp.setMaximum(40)
        self.dial_Temp.setObjectName(_fromUtf8("dial_Temp"))
        self.NewTemp = QtGui.QLCDNumber(self.TempTab)
        self.NewTemp.setGeometry(QtCore.QRect(240, 310, 141, 61))
        self.NewTemp.setFrameShape(QtGui.QFrame.NoFrame)
        self.NewTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.NewTemp.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.NewTemp.setObjectName(_fromUtf8("NewTemp"))
        self.ActualTemp = QtGui.QLCDNumber(self.TempTab)
        self.ActualTemp.setGeometry(QtCore.QRect(40, 30, 141, 61))
        self.ActualTemp.setFrameShape(QtGui.QFrame.NoFrame)
        self.ActualTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.ActualTemp.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.ActualTemp.setObjectName(_fromUtf8("ActualTemp"))
        self.TempBar = QtGui.QProgressBar(self.TempTab)
        self.TempBar.setGeometry(QtCore.QRect(130, 175, 111, 61))
        self.TempBar.setProperty("value", 24)
        self.TempBar.setTextVisible(False)
        self.TempBar.setObjectName(_fromUtf8("TempBar"))
        self.TempApp = QtGui.QPushButton(self.TempTab)
        self.TempApp.setGeometry(QtCore.QRect(703, 70, 61, 51))
        self.TempApp.setText(_fromUtf8(""))
        self.TempApp.setAutoDefault(True)
        self.TempApp.setDefault(True)
        self.TempApp.setFlat(True)
        self.TempApp.setObjectName(_fromUtf8("TempApp"))
        self.label_5 = QtGui.QLabel(self.TempTab)
        self.label_5.setGeometry(QtCore.QRect(376, 313, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.TempTab)
        self.label_7.setGeometry(QtCore.QRect(175, 31, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_3/tem.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.TempTab, icon2, _fromUtf8(""))
        self.LumTab = QtGui.QWidget()
        self.LumTab.setObjectName(_fromUtf8("LumTab"))
        self.LumC = QtGui.QLabel(self.LumTab)
        self.LumC.setGeometry(QtCore.QRect(0, 0, 807, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LumC.sizePolicy().hasHeightForWidth())
        self.LumC.setSizePolicy(sizePolicy)
        self.LumC.setText(_fromUtf8(""))
        self.LumC.setPixmap(QtGui.QPixmap(_fromUtf8("background/backLUMNew1.jpg")))
        self.LumC.setScaledContents(True)
        self.LumC.setObjectName(_fromUtf8("LumC"))
        self.dial_lum = QtGui.QDial(self.LumTab)
        self.dial_lum.setGeometry(QtCore.QRect(538, 151, 242, 234))
        self.dial_lum.setMaximum(255)
        self.dial_lum.setObjectName(_fromUtf8("dial_lum"))
        self.LumApp = QtGui.QPushButton(self.LumTab)
        self.LumApp.setGeometry(QtCore.QRect(703, 70, 61, 51))
        self.LumApp.setText(_fromUtf8(""))
        self.LumApp.setAutoDefault(True)
        self.LumApp.setDefault(True)
        self.LumApp.setFlat(True)
        self.LumApp.setObjectName(_fromUtf8("LumApp"))
        self.ActualLum = QtGui.QLCDNumber(self.LumTab)
        self.ActualLum.setGeometry(QtCore.QRect(20, 30, 141, 61))
        self.ActualLum.setFrameShape(QtGui.QFrame.NoFrame)
        self.ActualLum.setFrameShadow(QtGui.QFrame.Plain)
        self.ActualLum.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.ActualLum.setProperty("intValue", 0)
        self.ActualLum.setObjectName(_fromUtf8("ActualLum"))
        self.LumBar = QtGui.QProgressBar(self.LumTab)
        self.LumBar.setGeometry(QtCore.QRect(140, 241, 121, 61))
        self.LumBar.setMaximum(255)
        self.LumBar.setProperty("value", 24)
        self.LumBar.setTextVisible(False)
        self.LumBar.setObjectName(_fromUtf8("LumBar"))
        self.label_4 = QtGui.QLabel(self.LumTab)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_2/lum.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.LumTab, icon3, _fromUtf8(""))
        self.HumTab = QtGui.QWidget()
        self.HumTab.setObjectName(_fromUtf8("HumTab"))
        self.HumC = QtGui.QLabel(self.HumTab)
        self.HumC.setGeometry(QtCore.QRect(0, 0, 807, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HumC.sizePolicy().hasHeightForWidth())
        self.HumC.setSizePolicy(sizePolicy)
        self.HumC.setText(_fromUtf8(""))
        self.HumC.setPixmap(QtGui.QPixmap(_fromUtf8("background/humBackNEW.jpg")))
        self.HumC.setScaledContents(True)
        self.HumC.setObjectName(_fromUtf8("HumC"))
        self.ActualHum = QtGui.QLCDNumber(self.HumTab)
        self.ActualHum.setGeometry(QtCore.QRect(40, 30, 141, 61))
        self.ActualHum.setFrameShape(QtGui.QFrame.NoFrame)
        self.ActualHum.setFrameShadow(QtGui.QFrame.Plain)
        self.ActualHum.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.ActualHum.setObjectName(_fromUtf8("ActualHum"))
        self.HumRef = QtGui.QPushButton(self.HumTab)
        self.HumRef.setGeometry(QtCore.QRect(584, 210, 151, 141))
        self.HumRef.setText(_fromUtf8(""))
        self.HumRef.setFlat(True)
        self.HumRef.setObjectName(_fromUtf8("HumRef"))
        self.label_3 = QtGui.QLabel(self.HumTab)
        self.label_3.setGeometry(QtCore.QRect(180, 31, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_2/hum.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.HumTab, icon4, _fromUtf8(""))
        self.IrrigTab = QtGui.QWidget()
        self.IrrigTab.setObjectName(_fromUtf8("IrrigTab"))
        self.IrrigC = QtGui.QLabel(self.IrrigTab)
        self.IrrigC.setGeometry(QtCore.QRect(0, 0, 807, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IrrigC.sizePolicy().hasHeightForWidth())
        self.IrrigC.setSizePolicy(sizePolicy)
        self.IrrigC.setText(_fromUtf8(""))
        self.IrrigC.setPixmap(QtGui.QPixmap(_fromUtf8("background/irrigBack.jpg")))
        self.IrrigC.setScaledContents(True)
        self.IrrigC.setObjectName(_fromUtf8("IrrigC"))
        self.dial_Irrig = QtGui.QDial(self.IrrigTab)
        self.dial_Irrig.setGeometry(QtCore.QRect(538, 151, 242, 234))
        self.dial_Irrig.setMaximum(100)
        self.dial_Irrig.setSingleStep(10)
        self.dial_Irrig.setObjectName(_fromUtf8("dial_Irrig"))
        self.IrrigApp = QtGui.QPushButton(self.IrrigTab)
        self.IrrigApp.setGeometry(QtCore.QRect(703, 70, 61, 51))
        self.IrrigApp.setText(_fromUtf8(""))
        self.IrrigApp.setAutoDefault(True)
        self.IrrigApp.setDefault(True)
        self.IrrigApp.setFlat(True)
        self.IrrigApp.setObjectName(_fromUtf8("IrrigApp"))
        self.ActualIrrig = QtGui.QLCDNumber(self.IrrigTab)
        self.ActualIrrig.setGeometry(QtCore.QRect(40, 30, 141, 61))
        self.ActualIrrig.setFrameShape(QtGui.QFrame.NoFrame)
        self.ActualIrrig.setFrameShadow(QtGui.QFrame.Plain)
        self.ActualIrrig.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.ActualIrrig.setObjectName(_fromUtf8("ActualIrrig"))
        self.IrrigBar = QtGui.QProgressBar(self.IrrigTab)
        self.IrrigBar.setGeometry(QtCore.QRect(130, 175, 111, 61))
        self.IrrigBar.setProperty("value", 0)
        self.IrrigBar.setTextVisible(False)
        self.IrrigBar.setObjectName(_fromUtf8("IrrigBar"))
        self.NewIrrig = QtGui.QLCDNumber(self.IrrigTab)
        self.NewIrrig.setGeometry(QtCore.QRect(240, 310, 141, 61))
        self.NewIrrig.setFrameShape(QtGui.QFrame.NoFrame)
        self.NewIrrig.setFrameShadow(QtGui.QFrame.Plain)
        self.NewIrrig.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.NewIrrig.setObjectName(_fromUtf8("NewIrrig"))
        self.label = QtGui.QLabel(self.IrrigTab)
        self.label.setGeometry(QtCore.QRect(380, 313, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.IrrigTab)
        self.label_2.setGeometry(QtCore.QRect(180, 32, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon_set_2/irrig_2.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.IrrigTab, icon5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.dial_Irrig, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.NewIrrig.display)
        QtCore.QObject.connect(self.dial_Temp, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.NewTemp.display)
        QtCore.QObject.connect(self.dial_lum, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.LumBar.setValue)
        QtCore.QObject.connect(self.dial_Irrig, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.IrrigBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_8.setText(_translate("MainWindow", "°C", None))
        self.label_9.setText(_translate("MainWindow", "%", None))
        self.label_10.setText(_translate("MainWindow", "LUX", None))
        self.label_11.setText(_translate("MainWindow", "%", None))
        self.label_12.setText(_translate("MainWindow", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OverTab), _translate("MainWindow", "Overview", None))
        self.label_5.setText(_translate("MainWindow", "°C", None))
        self.label_7.setText(_translate("MainWindow", "°C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TempTab), _translate("MainWindow", "Temperature", None))
        self.label_4.setText(_translate("MainWindow", "LUX", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LumTab), _translate("MainWindow", "Luminosity    ", None))
        self.label_3.setText(_translate("MainWindow", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HumTab), _translate("MainWindow", "Humidity       ", None))
        self.label.setText(_translate("MainWindow", "%", None))
        self.label_2.setText(_translate("MainWindow", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IrrigTab), _translate("MainWindow", "Irrigation  ", None))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

